name: Build APK

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        build-type: [apk, appbundle]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Check contents of the directory
      - name: List directory contents
        run: ls -la

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: flutter-${{ env.FLUTTER_VERSION }}
          restore-keys: |
            flutter-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build the APK or AppBundle
      - name: Build APK or AppBundle
        run: |
          cd path/to/your/flutter/project  # استبدل بهذا المسار الصحيح
          flutter config --no-analytics
          flutter build ${{ matrix.build-type }} --verbose --build-name=${{ env.BUILD_VERSION }} --build-number=${{ env.BUILD_NUMBER }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build-type }}-build-artifact
          path: build/app/outputs/${{ matrix.build-type }}
          if-no-files-found: warn
          overwrite: false
